bottle:
  xpCost: 5
  useItems: true
  amountConsumed: 1
language:
  errAmount: The amount has to be a number!
  errXP: You don't have enough XP!
  currentXP: You currently have
  order1: You have ordered
  order2: bottles
  refund: Refund issued! Amount
  itemConsume: You don't have enough items!